server:
  port: 9092
spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}
        register: true
        register-health-check: false
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
    gateway:
      enabled: true
      loadbalancer:
        use404: true
      routes:
        -   id: app-service
            predicates:
              - Path=/api/**
            uri: lb://app
